### ISSUE TITLE
Add local Belgium postal codes database

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-maps#5]
**Remco**

> We kunnen ook alle Belgische postcodes en bijbehorende plaatsnamen opnemen in de plugin:
> 
> https://www.bpost2.be/zipcodes/files/zipcodes_num_nl_new.html
> 
> Dan ben je voor Belgische postcodes helemaal niet meer afhankelijk van externe webervices.
> 
> Nadeel kan zijn dat dat de datalijst op een gegeven moment verouderd raakt, maar dan kunnen we altijd de plugin weer updaten.

**KJ**

> ●●●●● wil graag toch een kleine aanpassing voor de Belgische sites. Het liefst - zoals jij voorstelde - met een extern databestand.

**Comment by remcotolsma** [comment]
Added support for this in https://github.com/pronamic/wp-pronamic-maps/commit/ffabc9edb4877b22bcd8a2e498c343b3eb888d3a, example request that will trigger this feature: `/wp-json/pronamic-maps/v1/address/autocomplete?country_code=BE&postcode=0612`.

**Comment by remcotolsma** [comment]
This was not correct, there are multiple postcodes with multiple places:

```
1350 | Enines | Ja | ORP-JAUCHE | WAALS-BRABANT
1350 | Folx-les-Caves | Ja | ORP-JAUCHE | WAALS-BRABANT
1350 | Jandrain-Jandrenouille | Ja | ORP-JAUCHE | WAALS-BRABANT
1350 | Jauche | Ja | ORP-JAUCHE | WAALS-BRABANT
1350 | Marilles | Ja | ORP-JAUCHE | WAALS-BRABANT
1350 | Noduwez | Ja | ORP-JAUCHE | WAALS-BRABANT
1350 | Orp-le-Grand | Ja | ORP-JAUCHE | WAALS-BRABANT
```

**Comment by kjtolsma** [comment]
@remcotolsma Ik heb dit nagevraagd. Volgens de accountant van Daadkracht Marketing vullen belgen altijd de hoofdgemeente in en wordt de plaats niet gebruikt. Dat zien ze ook terug in de aanvragen die ze binnen krijgen. Ik heb daarom een aanpassing gedaan. Zie: https://github.com/pronamic/wp-pronamic-maps/commit/002468fee3b24228d9f05bb40cc78c759e2201c0

**Comment by remcotolsma** [comment]
Nu gaan we een `municipality` ('gemeente' ) gebruiken als `city`, heeft de 'accountant' van Daadkracht Marketing ook een bron voor het volgende?

> Volgens de accountant van Daadkracht Marketing vullen belgen altijd de hoofdgemeente in en wordt de plaats niet gebruikt.

Ik heb hier wel mijn twijfels bij, op bijvoorbeeld https://des4seigneurs.be/contact/ zie je:

> Rue des quatre seigneurs 1
> 5575 Malvoisin-Gedinne

Waarbij `5575` de postcode is, `Malvoisin` plaatsnaam en `Gedinne` deelgemeente.

Op http://www.ardenne-essentielle.be/contact.html zie je:

> Rue de Porcheresse, 21
> B-6929 Gembes (Daverdisse)

Waarbij `6929` de postcode is, `Gembes` plaatsnaam en `Daverdisse` deelgemeente.

Postcode | Plaatsnaam | Deelgemeente | Hoofdgemeente | Provincie
-- | -- | -- | -- | --
6929 | Daverdisse | Neen | DAVERDISSE | LUXEMBURG
6929 | Gembes | Ja | DAVERDISSE | LUXEMBURG
6929 | Haut-Fays | Ja | DAVERDISSE | LUXEMBURG
6929 | Porcheresse | Ja | DAVERDISSE | LUXEMBURG

Als er toch meerdere "Rue de Porcheresse" straten in postcode gebied `6929` liggen weet je met alleen deelgemeente 'Daverdisse' niet naar welke plaats/straat het moet?

**Comment by kjtolsma** [comment]
@remcotolsma Zal het nog eens navragen op basis van deze voorbeelden.

**Comment by remcotolsma** [comment]
Via https://www.bpost.be/nl/faq/hoe-schrijf-ik-een-adres-correct-op-de-omslag en  https://www.bpost.be/site/nl/verzenden/brieven-en-kaarten/hoe-adresseer-ik-correct/een-adres-valideren hebben ze het ook over "Gemeente":

<img width="816" alt="Scherm­afbeelding 2023-01-25 om 08 50 06" src="https://user-images.githubusercontent.com/869674/214508411-4b5b467a-b2b8-44c4-86c8-925ee496ae5e.png">

Ik wil nog wel even bekijken of we hier wel het `city` veld voor moeten misbruiken:

https://github.com/pronamic/wp-pronamic-maps/blob/002468fee3b24228d9f05bb40cc78c759e2201c0/pronamic-maps.php#L434-L440

**Comment by remcotolsma** [comment]
Gravity Forms gebruikt voor de "City" `autocomplete` waarde ook `address-level2`:

<img width="301" alt="Scherm­afbeelding 2023-02-01 om 09 20 35" src="https://user-images.githubusercontent.com/869674/215989362-0898fcc3-805a-4da2-b414-8661f9654ae6.png">

> The second [administrative level](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#administrative_levels_in_addresses), in addresses with at least two of them. In countries with two administrative levels, this would typically be the city, town, village, or other locality in which the address is located.

Als wij de Belgische gemeente wegschrijven in `$address->level_2` en dit gebruiken in de onderliggende scripts is dat misschien nog wel het mooiste.
