### ISSUE TITLE
Even listener on autocomplete?

### ISSUE THREAD

**Issue by kjtolsma** [pronamic/wp-pronamic-maps#6]
On https://www.stratenmakers.in/ we have some simple JS validation on input fields. Is there a way to check if as field is autocompleted? I now added this:

```
// Event listener on autocompleted.
if ( data.address[ property ] ) {
	const autocompletedEvent = new CustomEvent( 'pm.input.autocompleted', {
		detail: {
			input_id: input.id
		}
	} );

	document.dispatchEvent( autocompletedEvent );
}
```

This works good. See video. Suggestions are welcome. Maybe this hasn't to be a plugin update, but i can't find any other solution how to fix this.

https://user-images.githubusercontent.com/1701552/151195549-6be89ce2-9887-4a77-8787-05d023e570e9.mov

**Comment by remcotolsma** [comment]
We have to find out whether it's good practice to trigger the `input` and/or `change` event on Pronamic Maps autocomplete:

- `input` = Fired at controls when the user changes the value (see also the change event)
   https://html.spec.whatwg.org/multipage/indices.html#event-change
- `change` = Fired at controls when the user commits a value change (see also the input event)
   https://html.spec.whatwg.org/multipage/indices.html#event-input

Technically the user does not change or commit the Pronamic Maps autocomplete value directly. But indirectly the user does cause the autocomplete and the value change. Do we therefore find it acceptable to dispatch a `input` and/or `change` event?

@rvdsteege do you have experience with this?

**Comment by rvdsteege** [comment]
No experience with browser behaviour of autocomplete specifically, but I'd trigger the `change` event on the element (instead of on `document`, so you don't need to pass the ID of the input field) whenever the value of an input field has changed programmatically.

**Comment by remcotolsma** [comment]
Just tested which events browser autocompletes triggers:

```
jQuery('#input_11_2').on( 'change', function() { console.log( 'change' ); } )
jQuery('#input_11_2').on( 'input', function() { console.log( 'input' ); } )
```

Both `input` (first) and `change` (second) events are triggered when using browser autocomplete feature.

**Comment by rvdsteege** [comment]
I'd do the same then; trigger both events.

**Comment by remcotolsma** [comment]
@kjtolsma We now trigger the `input` and `change` event in https://github.com/pronamic/wp-pronamic-maps/commit/f00c683ac0aecfa18fccbd487671e427ece6001f, removed the custom event handler in https://gitlab.com/pronamic-themes/dmb/-/commit/91b818bc446d0e5818d8fe15e7e3552e468e59a3.
