### ISSUE TITLE
Mark fields as readonly

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-maps#8]
I would like to mark the 'street' and 'city' fields as readonly and let Pronamic Maps autocomplete these fields.

<img width="1003" alt="Schermafbeelding 2022-02-02 om 15 46 29" src="https://user-images.githubusercontent.com/869674/152176865-f745e30b-c7bb-489b-be0b-feac3fcfb9d3.png">

Unfortunately Gravity Forms doesn't have native support for this:

- https://docs.gravityforms.com/making-a-field-read-only/
- https://www.gravityforms.com/add-ons/read-only/
- https://gravitywiz.com/documentation/gravity-forms-read-only/

Should we use the solution from Gravity Wiz or should we add this feature in for example the Pronamic Client plugin?

Maybe also related to the following issue:

- https://github.com/pronamic/wp-pronamic-maps/issues/7

In the above issue I mention:

> ```
> <input pattern="regexp">
> ```
>
> There is also the HTML input pattern attribute.
> https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern

The `pattern` attribute is also not supported in Gravity Forms afaik.

- https://wordpress.org/plugins/gravityforms-html5-validation/

Maybe handy to include some of these things in the Pronamic Client plugin?

**Comment by rvdsteege** [comment]
> Should we use the solution from Gravity Wiz or should we add this feature in for example the Pronamic Client plugin?

Would it not be possible to include this functionality, and (optionally?) enable when the address autocompletion is in use on a form? Always nice if basic functionality works out-of-the-box, without any other requirements.

**Comment by remcotolsma** [comment]
@rvdsteege I think there are use cases where a user wants to keep a street/city fields editable and another user wants to set these fields to readonly. It is never 100% certain that autocompletion will work, for Dutch addresses you only need postal code + house number, for international addresses it might be different?

**Comment by rvdsteege** [comment]
I understand and agree, therefore I added "optionally?" 😀

But as I read the issue, I thought a 2nd plugin would be required to make the fields read-only? So I wanted to add that it would be nice if the functionality would be included in the Pronamic Maps plugin itself (but can be enabled optionally per address field).

**Comment by remcotolsma** [comment]
Added support for a readonly checkbox:
https://github.com/pronamic/wp-pronamic-maps/blob/main/pronamic-maps.php#L595-L651

Demo:
https://www.eerstekamerbadkamers.nl/gravity-forms-automatisch-aanvullen-test/
