### ISSUE TITLE
Velden vullen nadat postcode én huisnummer is ingevuld

### ISSUE THREAD

**Issue by kjtolsma** [pronamic/wp-pronamic-maps#9]
Is het mogelijk om de adresvelden te vullen nadat zowel de postcode als huisnummer ingevuld is?

https://www.stratenmakers.in/offerte-aanvragen/

Het huisnummer veld komt op hier straks op positie 2. Na het invullen van "Postcode" en "Huisnummer" zou de "Woonplaats" en "Adres" gevuld moeten worden.

**Comment by remcotolsma** [comment]
Dat is momenteel niet mogelijk, heeft ook niet heel veel meerwaarde? Op basis van een postcode kan immers vaak "Woonplaats"en "Adres" al aangevuld worden. Mocht dat niet lukken omdat er toch een huisnummer nodig is dan wordt "Woonplaats" en "Adres" wel aangevuld zodra er een huisnummer wordt ingevoerd.

**Comment by remcotolsma** [comment]
> Mocht dat niet lukken omdat er toch een huisnummer nodig is dan wordt "Woonplaats" en "Adres" wel aangevuld zodra er een huisnummer wordt ingevoerd.

Dit is niet juist, voor huisnummer is nog niet een gestandaardiseerde `autocomplete` waarde:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

Er lijkt wel een discussies gaande te zijn met een voorstel om een optie voor o.a. huisnummer toe te voegen:

- https://github.com/whatwg/html/issues/4986

Voorkeur van iemand:

> FWIW I would prefer `address-line1-street-name` and `address-line1-house-number`.

https://github.com/battre/autocomplete-attribute-explainer/tree/main

Ik neig zelf meer naar gewoon simpel `house-number` net als gewoon simpel `postal-code`.

**Comment by kjtolsma** [comment]
Ik zou ook voor `house-number` gaan. Zoals je zegt komt dat het meest overeen met `postal-code`.

**Comment by remcotolsma** [comment]
Probleem is alleen dat Gravity Forms geen eigen bedachte `autocomplete` waarden accepteert:

https://github.com/pronamic/gravityforms/blob/f95ddc0c9b7087898e94d4fd79ce5020803d2c1c/includes/fields/class-gf-field.php#L2287-L2333

Als we dit willen implementeren dan moeten we de huidige PDOK aanroep denk ik ook wijzigen:
https://geodata.nationaalgeoregister.nl/locatieserver/v3/free?q=1097DN&fq=type:postcode

We moeten dan eigenlijk niet meer alleen postcode informatie opvragen (`fq=type:postcode`).

- https://geodata.nationaalgeoregister.nl/locatieserver/v3/free?q=1097DN
- https://geodata.nationaalgeoregister.nl/locatieserver/v3/free?q=1097DN&fq=type:postcode
- https://geodata.nationaalgeoregister.nl/locatieserver/v3/free?q=postcode:1097DN%20and%20huisnummer:10
- https://geodata.nationaalgeoregister.nl/locatieserver/v3/free?q=postcode:1097DN%20and%20huisnummer:10&fq=type:adres

**Comment by remcotolsma** [comment]
> Het is lastig om dit via code op te splitsen door de vele mogelijke notaties:
> 
> > Witbreuksweg 307-309. Dat is dan gebouw 307, verdieping 3, kamer 9. Het eigenlijke huisnummer is 307, dus oneven.
> 
> _Bron:_ https://nl.wikipedia.org/wiki/Huisnummer#Toevoegingen

Dit valt misschien ook wel mee, via een regulier expressie de eerste nummers pakken:

`([0-9]+).*`

**Comment by remcotolsma** [comment]
> > Probleem is alleen dat Gravity Forms geen eigen bedachte autocomplete waarden accepteert:
> 
> Dit kan misschien als volgt opgelost worden:
> 
> | `autocomplete`  | `property`     |
> | --------------- | -------------- |
> | `address-line1` | `street_name`  |
> | `address-line2` | `house_number` |
> | `address-line3` | `house_letter` |

Besproken dat dit misschien toch niet heel fraai is, het is toch een beetje misbruik maken van de ``address-line1`, `address-line2` en `address-line3` opties.

In Nederland wordt de naam (regel 1), straatnaam en huisnummer (regel 2) en postcode en plaatsnaam (regel 3) ook wel als adresregels gezien.

---

<img width="569" alt="Schermafbeelding 2022-04-20 om 09 16 35" src="https://user-images.githubusercontent.com/869674/164172238-34c02b2b-5672-4d52-8f0b-dcac105a6a4e.png">

---

https://www.postnl.nl/versturen/brief-of-kaart-versturen/hoe-verstuur-ik-een-brief-of-kaart/brief-adresseren/

Een apart veld maken voor Gravity Forms waarin opgegeven kan worden wat de Pronamic Maps autocomplete waarde moet zijn is dan waarschijnlijk mooier.

**Comment by kjtolsma** [comment]
Wat mij betreft laten we dit eerst voor wat het is.
